export const GET_TIMEFRAME_LIST_REQUEST = "GET_TIMEFRAME_LIST_REQUEST";
export const GET_TIMEFRAME_LIST_SUCCESS = "GET_TIMEFRAME_LIST_SUCCESS";
export const GET_TIMEFRAME_LIST_FAIL = "GET_TIMEFRAME_LIST_FAIL";

export const UPDATE_TIMEFRAME_REQUEST = "UPDATE_TIMEFRAME_REQUEST";
export const UPDATE_TIMEFRAME_SUCCESS = "UPDATE_TIMEFRAME_SUCCESS";
export const UPDATE_TIMEFRAME_FAIL = "UPDATE_TIMEFRAME_FAIL";

export const ADD_TIMEFRAME_REQUEST ="ADD_TIMEFRAME_REQUEST"
export const ADD_TIMEFRAME_SUCCESS="ADD_TIMEFRAME_SUCCESS"
export const ADD_TIMEFRAME_FAIL="ADD_TIMEFRAME_FAIL"

export const DELETE_TIMEFRAME_REQUEST ="DELETE_TIMEFRAME_REQUEST"
export const DELETE_TIMEFRAME_SUCCESS="DELETE_TIMEFRAME_SUCCESS"
export const DELETE_TIMEFRAME_FAIL="DELETE_TIMEFRAME_FAIL"
